<a href="https://colab.research.google.com/github/sk964396/NUMPY/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(9)

9


Basic array creation


In [ ]:
import numpy as np


In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
print(np.array([1,2,3,4,5,"ello"]))

['1' '2' '3' '4' '5' 'ello']


In [ ]:
b=np.arange((1,10))

In [ ]:
print(b)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr2=np.zeros(6)
arr2

array([0., 0., 0., 0., 0., 0.])

In [ ]:
arr3=np.zeros((6,6))
arr3

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
arr=np.ones(9)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
arr=np.ones((9,9))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
arr=np.linspace(1,100,80)
arr

array([  1.        ,   2.25316456,   3.50632911,   4.75949367,
         6.01265823,   7.26582278,   8.51898734,   9.7721519 ,
        11.02531646,  12.27848101,  13.53164557,  14.78481013,
        16.03797468,  17.29113924,  18.5443038 ,  19.79746835,
        21.05063291,  22.30379747,  23.55696203,  24.81012658,
        26.06329114,  27.3164557 ,  28.56962025,  29.82278481,
        31.07594937,  32.32911392,  33.58227848,  34.83544304,
        36.08860759,  37.34177215,  38.59493671,  39.84810127,
        41.10126582,  42.35443038,  43.60759494,  44.86075949,
        46.11392405,  47.36708861,  48.62025316,  49.87341772,
        51.12658228,  52.37974684,  53.63291139,  54.88607595,
        56.13924051,  57.39240506,  58.64556962,  59.89873418,
        61.15189873,  62.40506329,  63.65822785,  64.91139241,
        66.16455696,  67.41772152,  68.67088608,  69.92405063,
        71.17721519,  72.43037975,  73.6835443 ,  74.93670886,
        76.18987342,  77.44303797,  78.69620253,  79.94

**RANDOM GENERATION FUNCTION**

In [ ]:
import numpy as np


In [ ]:
np.random.rand(10)

array([0.33004959, 0.68361031, 0.5677553 , 0.89397347, 0.94920982,
       0.85454605, 0.09144764, 0.75171864, 0.46338432, 0.29024546])

In [ ]:
np.random.randn(10)

array([ 0.14871395, -0.00713129,  0.27687551,  0.89117898,  1.42752541,
       -0.16801721, -0.45489359,  0.36712521,  0.35942762,  0.41437171])

In [ ]:
np.random.randint(1,100,100)

array([85, 15, 45, 78, 85, 59, 85, 61, 18, 75, 47, 12, 45, 21, 58, 30, 97,
       17, 28, 50, 95,  9, 94,  4, 60,  2, 20, 48, 68, 80, 86, 14, 22, 78,
       18, 76, 80, 65,  4, 67, 78, 99, 19, 51, 14, 17, 74, 41, 26, 29, 39,
       45, 77, 81, 46, 23, 92, 31,  3, 54,  8, 62, 30,  4, 71, 46, 11, 31,
       94, 64, 50, 91, 74, 85, 44, 66, 64, 18, 28, 28, 73, 75, 34, 99,  2,
       17, 67, 30, 84, 29, 80, 73, 53,  8, 73, 80, 44, 36, 60, 36])

**ARRAY ATTRIBUTES**

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,9,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 9]])

In [ ]:
arr.shape


(3, 3)

In [ ]:
arr.size

9

**ARRAY METHODS**

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 9, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(46)

In [ ]:
np.sum(arr,axis=0)

array([12, 16, 18])

In [ ]:
arr.mean()

np.float64(5.111111111111111)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.argmax()

np.int64(7)

In [ ]:
arr.argmin()

np.int64(0)

**RESHAPING AND RESIZING**

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

**NUMPY INDEXING AND SLICING OF VECTORS**

In [ ]:
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr[9]

np.int64(10)

In [ ]:
arr[1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr[0::4]

array([ 1,  5,  9, 13, 17, 21, 25, 29])

**NUMPY INDEXING AND SLICING OF MATRIX**

In [ ]:
arr=np.arange(1,31).reshape(5,6)

In [ ]:
arr


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [ ]:
arr[0:3,0:3]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]])

In [ ]:
arr[2:5,4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

**BOOLEAN INDEXING**

In [ ]:
arr=np.arange(11,21)

In [ ]:
arr


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index=arr/2==0

In [ ]:
bool_index

array([False, False, False, False, False, False, False, False, False,
       False])

In [ ]:
arr=arr[bool_index]

In [ ]:
arr

array([], dtype=int64)

**ARRAY OPERATIONS**

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
a1+a2

array([ 7,  9, 11, 13, 15])

In [ ]:
a1*a2

array([ 6, 14, 24, 36, 50])

In [ ]:
 a1/a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

**BROADCASTING**

In [ ]:
L=[10,20,30,40]
arr=np.array(L)

In [ ]:
arr+10

array([20, 30, 40, 50])

**Deep and shallow copy**

**MATRIX MULTIPLICATION
**

In [ ]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[1,2,5],[4,7,9],[0,3,9]])
np.dot(a,b)

array([[  9,  25,  50],
       [ 24,  61, 119],
       [ 39,  97, 188]])

**tranpose**

In [ ]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

column stack.v stack.h stack


split